import { COLUMN_NAMES } from './constants';

const { UNSORTED } = COLUMN_NAMES;
export const tasks = [
  {
    name: 'Cleaning',
    includes: 'vacuum, wipe, dust, sanitize, etc.',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Dishes',
    includes: 'wash, dry, load, unload',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Trash',
    includes: 'take to the curb/shoot, replace bags',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Groceries',
    includes: 'keep a list, shop for food',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Home Supplies',
    includes: 'keep a list, shop for detergent, tootpaste, etc.',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Home Furnishings',
    includes: 'keep a list, shop for pillows, towels, etc.',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Maintenance',
    includes: 'unclog toilets, call handyman, etc.',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Home Purchase/Rental',
    includes: 'insurance, review options/statements',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Hosting',
    includes: 'send invites, plan menu, decorate',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Laundry',
    includes: 'wash/dry, fold, store',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Lawn & Plants',
    includes: 'mow, water, landscape',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Mail',
    includes: 'retrieve, open, and send',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Breakfast',
    includes: 'plan menu, cook',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Dinner',
    includes: 'plan menu, cook',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Money Management',
    includes: 'budget, long-term planing, taxes',
    standards: '',
    column: UNSORTED,
  },
  { name: 'Storage, Garage, & Donations', standards: '', column: UNSORTED },
  {
    name: 'Tidying',
    includes: 'make bed, clear countertops and floors',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Auto',
    includes: 'registration, insurance, maintenance, gas',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Calendar',
    includes: 'schedule and maintain',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  { name: 'Pay Bills', isDaily: true, standards: '', column: UNSORTED },
  {
    name: 'Charity & Community Service',
    includes: 'give back time and money',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Civic Engagement & Cultural Enrichment',
    includes: 'research and plan community events',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Tech',
    includes: 'fix/get help for issues, buy new items',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'First-Aid, Safety & Emergency',
    includes: 'stock supplies, make plans',
    standards: '',
    column: UNSORTED,
  },
  { name: 'Points, Miles, & Coupons', standards: '', column: UNSORTED },
  { name: 'Returns & Store Credit', standards: '', column: UNSORTED },
  {
    name: 'Social Plans',
    includes: 'sync calendars, pick time and place, invites',
    standards: '',
    column: UNSORTED,
  },
  { name: 'Vacations & Trips', includes: '', standards: '', column: UNSORTED },
  {
    name: 'Grooming & Wardrobe (Partner 1)',
    includes: 'appointments, shopping',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Grooming & Wardrobe (Partner 2)',
    includes: 'appointments, shopping',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Estate Planning & Life Insurance',
    includes: 'plan and arrange',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Health Insurance',
    includes: 'paperwork, track reimbursements',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Parents',
    includes: 'facilitate conversations and meet-ups',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Pet',
    includes: 'food, vet, supplies, grooming, walks/litter',
    isDaily: true,
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Extended Family',
    includes: 'reconnect, remember invites',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Fun & Dates',
    includes: 'schedule and plan',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Gifts',
    includes: 'meaningful gifts and cards for others',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Holidays',
    includes: 'cook, decorate, organize',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Spirituality',
    includes: 'plan attendance, rituals, and events, and enforce beliefs',
    standards: '',
    column: UNSORTED,
  },
  {
    name: 'Medicine & Healthy Living',
    includes: 'research, stock health-related items',
    standards: '',
    column: UNSORTED,
  },
];
